name: Clean Packages
# short list packages names
# gh api --jq '.[].name' -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "page: 2" -H "Per_page: 100" "/orgs/GemunIon/packages?package_type=npm" > pkglist.txt


# gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/GemunIon/packages/npm/nest-js-module-firebase/versions/102391991"
# gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/orgs/GemunIon/packages/npm/nest-js-module-firebase/versions"

on:
  workflow_dispatch:

jobs:
  clean:
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix:
        package: [
          'types-coin-market-cap',
          'provider-user-firebase',
          'provider-user-jwt',
          'markdown',
          'types-coingecko',
          'provider-api',
          'history',
          'provider-user',
          'yup-rules',
          'provider-settings',
          'constants',
          'firebase',
          'types-collection',
          'popup',
          'types-jwt',
          'draft-js-utils',
          'constants-regexp',
          'constants-validation',
          'types-email',
          'provider-popup',
          'types-coin-gecko',
          'types-blockchain',
          'yup-rules-eth',
          'provider-api-firebase',
          'provider-api-jwt',
          'types-iex-cloud',
          'utils',
          'butils',
          'provider-network',
          'redis'
        ]
    runs-on: ubuntu-latest

    steps:
      - name: clean package
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.package }}
          package-type: 'npm'
          min-versions-to-keep: 10
      - name: Sleep for 3 sec
        run: sleep 3s
        shell: bash
